# Generated by Django 2.2 on 2019-12-04 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='questions',
        ),
        migrations.AddField(
            model_name='exam',
            name='q1',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='exam',
            name='q10',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='exam',
            name='q2',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='exam',
            name='q3',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='exam',
            name='q4',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='exam',
            name='q5',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='exam',
            name='q6',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='exam',
            name='q7',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='exam',
            name='q8',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='exam',
            name='q9',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
