# Generated by Django 2.2 on 2019-12-04 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20191204_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='exam',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.Exam'),
        ),
    ]
